### ISSUE TITLE
Error with WebSockets and UTF-8 encodings

### ISSUE THREAD

**Issue by marcosnils** [franela/play-with-docker#10]
If within an instance you write `curl www.google.com` you'll see that the javascript console shows: `WebSocket connection to 'ws://play-with-docker.com/sessions/952dc23e-c830-40e2-ba0d-35ec548d0127/instances/goofy_keller/attach' failed: Could not decode a text frame as UTF-8.` and terminal stops working

**Comment by xetorthio** [comment]
Related to this is that maybe we should switch to socket.io. It has lots of
fallbacks and seems to sve all these crazy issues.

**Comment by marcosnils** [comment]
@akalipetis might help us with this :)

**Comment by akalipetis** [comment]
I think we could go with Socket.io - @alexellis also had an issue connecting to WebSockets over a proxy. I might jump into this sometime during the week 🎉

**Comment by marcosnils** [comment]
@akalipetis @xetorthio found the problem :D

**Comment by akalipetis** [comment]
🎆🎇✨🎉

That needed a huge amount of code 😂
