### ISSUE TITLE
List of exposed ports should be stable (probably also be sorted)

### ISSUE THREAD

**Issue by lindt** [franela/play-with-docker#100]
When I run
```!sh
docker run -d -p 80:80 -p 443:443 nginx
```
Then ports 80 and 443 are opened.
These exposed ports are also displayed in the UI next to the IP.
There nearly each time the script checks the exposedd ports the order in which they are displayed changes.

Wouldn't it be nicer if these portlists are stable, probably also sorted?
Maybe by port number and/or by time the container with the exposed port has been started.

The current flickering just indicates a change, but in fact nothing changed.

**Comment by xetorthio** [comment]
Yes. Good catch. Sorting probably is the best option.

**Comment by lindt** [comment]
thanks for the fix!
