### ISSUE TITLE
Can't connect to a published port from the outside world.

### ISSUE THREAD

**Issue by bingohuang** [franela/play-with-docker#104]
First, Thank all of you for this project, I really like it.

I play  with the live version:  http://play-with-docker.com. But  I can't connect to a published port from the outside world ,  although I  follow the FAQ in  the README.md.

![image](https://cloud.githubusercontent.com/assets/3715340/23733226/c756911a-04b2-11e7-89d4-829b978606a1.png)

How  can I do this?

Thanks.

**Comment by marcosnils** [comment]
@bingohuang try this:

`docker run -p 8080:80 nginx`

You'll see that a small badge icon (image below) will appear next to the instance IP
![image](https://cloud.githubusercontent.com/assets/1578458/23733635/db1728f4-0458-11e7-85f7-931499c72f2a.png)


If you click that link, you'll be able to access the instance published services.
