### ISSUE TITLE
add in AppArmor

### ISSUE THREAD

**Issue by ManoMarks** [franela/play-with-docker#105]
Adding AppArmor would allow us to do security tutorials like this:
https://github.com/docker/labs/tree/master/security/apparmor

**Comment by marcosnils** [comment]
![image](https://cloud.githubusercontent.com/assets/1578458/24336141/58363acc-1260-11e7-9eee-5e04a85f046b.png)


apparmor has been enabled. @ManoMarks take into account that current labs will need to be tweaked as `alpine` doesn't have apparmor binaries to display applied profiles.
