### ISSUE TITLE
can't connect to docker enpoint

### ISSUE THREAD

**Issue by allamand** [franela/play-with-docker#108]
Hello,

I'm not able to connect with my docker CLI to my PWD instance

While making a docker ps, I see in pwd logs : 
```
pwd    | 2017/03/13 16:26:32 http: proxy error: dial tcp 10.0.4.3:80: getsockopt: connection refused
pwd    | [negroni] 2017-03-13T16:26:32Z | 502 |          1.356175ms | pwd10_0_4_3-2375.pwd.server.com:80 | GET /_ping 
```

When using docker cli the port output of getTargetInfo is 80 instad of 2375 so that doesn't works.

```
$ export DOCKER_HOST="tcp://pwd10_0_14_3-2375.play-with-docker.com:80"
$ docker ps
Error: request returned Bad Gateway for API route and version http://pwd10_0_14_3-2375.play-with-docker.com:80/v1.26/containers/json, check if the server supports the requested API version
```

If I do simple curl, then It reach the docker API (the getTargetInfo output the port on 2375 which is what I want)

```
$ curl http://pwd10_0_14_3-2375.play-with-docker.com:80/v1.26/containers/json
[]
```

I can't figure out where comes the problem, do you have any though ?

**Comment by allamand** [comment]
in the getTargetInfo function, I've added this part in order to allow my request

```
        // give priority to the URL host port                                                                                                                                                                                                
        if len(hostPort) > 1 && hostPort[1] != config.PortNumber && hostPort[1] != "80" {
                port = hostPort[1]
        } else if port == "" {
                port = "80"
        }
```

in fact because PWD is running in docker, the config.PortNumber inside the container (3000) may be different from the real PWD port Number (80 in my case)

I'm not sure to understand correctly the priority for the hostPort, but adding this seams to work..

**Comment by marcosnils** [comment]
hey @allamand !. We did some changes in the PWD networking layer recently. It's easier to use the docker daemon. `export DOCKER_HOST="tcp://pwd10_0_14_3.play-with-docker.com` (without ports) should work now.

**Comment by allamand** [comment]
@marcosnils I try to uses without ports but didn't works. does that mean that I have to open port 2375 on my firewall targeting pwd ?

**Comment by marcosnils** [comment]
> @marcosnils I try to uses without ports but didn't works. does that mean that I have to open port 2375 on my firewall targeting pwd ?

Well.. outgoing unprivileged ports are usually opened unless you're using some kind of proxy. Depending if you're hosting PWD or you're trying to connect through it. 
In any case, this issue is closed as connecting to the daemon works like I posted above.

**Comment by allamand** [comment]
@marcosnils it's on my instance of PWD, but i don't understant how you've routed the 2375 port from internet to PWD.. you've added a port section in the docker-compose ? Thanks
