### ISSUE TITLE
Seams to be a bug in routage to containers

### ISSUE THREAD

**Issue by allamand** [franela/play-with-docker#115]
Hello,

I just create a PWD session, and start an nginx container : 

`docker run -d -p 80:80 nginx` ==> it gives me a clickable link to my nginx instance :)

But if now I start another container : 

`docker run -d -p 81:80 emilevauge/whoami` ==> it gives me a clickable link for port 81 but I reach nginx!!

If I remove nginx, then both links points to my whoami docker..

On my private PWD instance, once I've launched my nginx, then my pwd don't respond all traffic is respond by the nginx container.. I'm goint crazy with this stuff @marconil If you could give an eye on it ?

thanks

**Comment by marcosnils** [comment]
@allamand just tried this and it works as expected. Are you sure that when you click the `81` container, you're being directed to the URL with the port `81` on it?

I.E http://pwdx_x_x_x-**81**.host2.labs.play-with-docker.com/

**Comment by allamand** [comment]
@marcosnils ok, I just try again

http://host3.labs.play-with-docker.com/p/be270d56-2327-447a-958e-fe060473efab#be270d56_node1

I get nginx here :  http://pwd10_0_7_3-80.host3.labs.play-with-docker.com/

Then akward thing my previous url is my nginx responding.. http://host3.labs.play-with-docker.com/p/be270d56-2327-447a-958e-fe060473efab#be270d56_node1

**Comment by allamand** [comment]
When I said my PWD was responding with the content of the container It was that : 
![image](https://cloud.githubusercontent.com/assets/8956643/24612334/4fbf53ee-1885-11e7-95a0-dfccbfaba0ec.png)

**Comment by marcosnils** [comment]
I'll close I can't reproduce. We've realized that it works well with `curl`, so it seems like local browser related issue.

**Comment by allamand** [comment]
@marcosnils the problem is on our corporate proxy which makes misterious caching features, no problem with PWD itself :) , sorry for the burden
