### ISSUE TITLE
Prevent denial of service - disk flooding

### ISSUE THREAD

**Issue by alexellis** [franela/play-with-docker#13]
Run this... 

`dd if=/dev/zero of=filename bs=$((1024*1024)) count=$((10*1024))`

And the whole service will grind to a halt and stop functioning.

Perhaps need to add / enforce a disk size quota on containers.

**Comment by xetorthio** [comment]
Hey Alex! You really rock! :)

Yes. We need to add all kind of limitations, probably with cgroups. Like: disk usage, memory and CPU.

Any suggestion on how we can do that? /cc @marcosnils

**Comment by alexellis** [comment]
You're welcome - I tried out a memory limit on my laptop it appeared to work. Most restrictions are applied through config in the Docker API when creating the DIND containers.

**Comment by marcosnils** [comment]
We need to make host docker engine to use devicemapper that way we can restrict the amount of disk that containers can use. I'll try to fix thissome time this weekend

**Comment by marcosnils** [comment]
PWD is currently using devicemapper and a limit of 10gb per container
