### ISSUE TITLE
Delete terminal automatically if exec session exists

### ISSUE THREAD

**Issue by marcosnils** [franela/play-with-docker#15]
if you exit the shell by either `exit` or ctrl + d the exec session will end and all other terminal will remain unresponsive. It'd be nice to warn the user about this action and automatically delete terminals if action is intentional.

**Comment by xetorthio** [comment]
???

**Comment by marcosnils** [comment]
Dind shell can't be exited anymore. If sh session gets killed it will relaunch. The only way to delete an instance now is by the delete button
