### ISSUE TITLE
Limit the amount of processes

### ISSUE THREAD

**Issue by alexellis** [franela/play-with-docker#2]
Just an idea - maybe limit the amount of processes?

```
/ # ulimit -p
524288
```

Could maybe do make a mess if someone fork bomb'd 5x524288 processes?

**Comment by xetorthio** [comment]
That's a good idea. Where exactly we should set the ulimit?

**Comment by alexellis** [comment]
There's some data here:

https://devlearnings.wordpress.com/2014/08/22/limiting-fork-bomb-in-docker/

I think under the hood it's going to use a cgroup.

You may also want to lock down memory etc.

**Comment by alexellis** [comment]
PR - #4 

Repro:

```shell
#!/bin/sh
lol(){
let "i=0"

while true
do
    let "i=i+1"

    echo "looping... $i"
    sleep 2 &
done
}

lol
```

**Comment by marcosnils** [comment]
#4
