### ISSUE TITLE
http://play-with-docker.com/ broken?

### ISSUE THREAD

**Issue by mikemadden42** [franela/play-with-docker#42]
Is http://play-with-docker.com/ broken?  When I click on 'ADD NEW INSTANCE' it doesn't seem to do anything.  It was working yesterday.

**Comment by marcosnils** [comment]
Works for me. U still having issues?

sent from mobile

**Comment by mikemadden42** [comment]
Yes, it still is not working.  I've tried using the site from the latest version of Firefox & Google Chrome.

**Comment by xetorthio** [comment]
Yeah. We are working on making the service reliable. There are a few things to harden, specially from the security side.
