### ISSUE TITLE
Error response from daemon: driver name: if driver is specified name is required

### ISSUE THREAD

**Issue by alexellis** [franela/play-with-docker#5]
I did a `go get` and `go build` with go 1.7.1 and Docker  1.12.2-rc1. This is what happened when I hit "localhost:3000/"

Commenting out the Driver portion let me work around the issue but used bridge for the driver.

``` shell
[negroni] Started GET /
2016/10/09 19:06:17 NewSession id=[dc341e92-970c-44ef-aa18-0b80d60e4ed9]
2016/10/09 19:06:17 Starting session err [Error response from daemon: driver name: if driver is specified name is required]
2016/10/09 19:06:17 Error response from daemon: driver name: if driver is specified name is required
[negroni] Completed 0  in 8.6795ms
```

**Comment by marcosnils** [comment]
@alexellis you need docker 1.13-dev or higher in order to run the playground. Which version are you running against to?

**Comment by alexellis** [comment]
I was using 1.12 - it did work well if I don't pass the driver as an argument to the API. I'll try it now since the recent changes have gone in.
