### ISSUE TITLE
Bug: nano editor doesn't work

### ISSUE THREAD

**Issue by alexellis** [franela/play-with-docker#52]
```
# apk --update add nano
# nano
```

Type in some text then do control + w control + x ... it doesn't work - just hangs. I think mandating `vi` will be an issue for the groups I'd be working with.

Is this to do with the remapping of disconnect keys?

**Comment by xetorthio** [comment]
No worries. There must be a solution.

**Comment by marcosnils** [comment]
> Is this to do with the remapping of disconnect keys?

Yes, I believe that if you do ctrl-w + ctrl+x twice it should work. We've tried to use a combination that doesn't affect users but seems like we're running out of options. We can try a different preset

**Comment by alexellis** [comment]
@xetorthio still getting stuck with this. I think nano is going to be a must have for beginners.. `vi` will be a high barrier to entry

**Comment by marcosnils** [comment]
@alexellis this should be resolved. Please reopen if it doesn't work for you
