### ISSUE TITLE
Dockerize app

### ISSUE THREAD

**Issue by marcosnils** [franela/play-with-docker#6]
We need a dockerfile that builds this app :smile:

**Comment by alexellis** [comment]
I can help with that.

**Comment by alexellis** [comment]
```
FROM golang:1.7.1
RUN mkdir -p /go/src/github.com/franela/play-with-docker

# Run this in ahead of time to cache the step.
RUN go get -d github.com/docker/docker

COPY . /go/src/github.com/franela/play-with-docker/
WORKDIR /go/src/github.com/franela/play-with-docker/

RUN go get
RUN go build

CMD ["/bin/bash"]
```

I got this far - but the `-d` flag is getting ignored and this `go get` appears to try to build docker and fail.

**Comment by marcosnils** [comment]
@alexellis I think I know what might be happening here. I'll check it out later day.

**Comment by xetorthio** [comment]
I added a very basic support for this.
