### ISSUE TITLE
Add usage metrics

### ISSUE THREAD

**Issue by xetorthio** [franela/play-with-docker#60]
We could publish metrics so `prometheus` can collect them and keep track of things like:
- Number of sessions opened
- Number of instances opened

We can eventually add more important metrics :)

**Comment by marcosnils** [comment]
@xetorthio this can be closed right?

**Comment by marcosnils** [comment]
@xetorthio :bell: :snail:

**Comment by xetorthio** [comment]
Yes. We can close it
