### ISSUE TITLE
Getting errors when running on Docker4Mac beta31

### ISSUE THREAD

**Issue by DieterReuter** [franela/play-with-docker#61]
I'm trying to run PWD locally on my Mac in D4M beta31 (Docker 1.13.0-rc2).

I get to the main webpage and accept the captcha and will be redirected to a blank page and getting the following errors on the console:
```
2016/12/01 05:53:56 NewSession id=[171c7cec-349c-47f7-95fc-a63e3b090cbf]
2016/12/01 05:53:56 Starting session err [Error response from daemon: datastore for scope "global" is not initialized]
2016/12/01 05:53:56 ERROR NETWORKING
2016/12/01 05:53:56 Error response from daemon: datastore for scope "global" is not initialized
[negroni] Completed 0  in 550.306066ms
```

Would be nice to get some help or at least some hints where to dig deeper to analyse the problem. Running PWD in D4M could be pretty easy to set up and demo w/o the need to install and maintain additional hypervisors. at all.

**Comment by marcosnils** [comment]
Installing and configuration instructions have been updated in the README. @alexellis you can try it out now also.

**Comment by DieterReuter** [comment]
Issues could be easily resolved with
1) use Docker host in swarm mode `docker init swarm`
2) start PWD with `docker-compose up`
