### ISSUE TITLE
Cut / Copy is not working

### ISSUE THREAD

**Issue by medined** [franela/play-with-docker#65]
I started a new instance. Then ran 'docker swarm init'. The command worked but I could not highlight the text then right-click to copy. Nor could I use ^c.

Is there another keyboard combo I should be using?

**Comment by marcosnils** [comment]
Ctrl+shift+c/v

sent from mobile

**Comment by Oliboy50** [comment]
@medined agreed, it's a real issue on Firefox using Windows, because I'm able to copy using right click, but I'm not able to paste after this... but at least, I can copy/paste using right click on Chrome using Windows

@marcosnils this trick doesn't work on Windows (either using Chrome or Firefox)

**Comment by marcosnils** [comment]
@Oliboy50 haven't tested on windows. I'll give it a try

**Comment by Oliboy50** [comment]
@marcosnils after trying harder, it seems that CTRL+SHIFT+V work on Chrome, but CTRL+SHIFT+C opens the Chrome console panel instead of copy stuff

**Comment by marcosnils** [comment]
@Oliboy50 @akalipetis I believe this could be configured in xterm.js but we haven't looked in detail. Woudl you like to investigate and send a PR maybe?

**Comment by marcosnils** [comment]
Fixed. 

Added new shortcut to copy with ctrl + alt + v. Couldn't change default pasting due tu browser permissions.

Also, just found that ctrl + insert (copy) and shitft + insert(paste) should also work.

**Comment by Oliboy50** [comment]
I tried what you suggested, but none of this worked in Firefox on Windows :/

**Comment by marcosnils** [comment]
@Oliboy50 ctrl + shift +v should work for pasting as well as shift + insert. Can you please verify?

**Comment by Oliboy50** [comment]
@marcosnils 
- ctrl + shift + v is the [Adblock Plus](https://adblockplus.org/en/) default shortcut for opening the filtered elements list of the current page... so it does something else for me
- shift + insert does not work... However, it prints `^[[2~` when I use it twice

**Comment by marcosnils** [comment]
> ctrl + shift + v is the Adblock Plus default shortcut for opening the filtered elements list of the current page... so it does something else for me

I don't see that there's much we can do if a non-default browser plugin is interfering with xterm.js shortcuts =(. Maybe you can change Adblock plus default shortcut?

**Comment by Oliboy50** [comment]
@marcosnils I deactivated the Adblock Plus shortcut, but ctrl + shift + v does not work, it does nothing at all :(

**Comment by Oliboy50** [comment]
seems like there is an issue opened on xterm.js side https://github.com/sourcelair/xterm.js/issues/418

**Comment by marcosnils** [comment]
@Oliboy50 interesting. I'll check it out and come back to you here.

**Comment by marcosnils** [comment]
@Oliboy50 just downloaded latest firefox 51.0.1 in Windows 10 and shift + insert works perfectly. ctrl + shift + v doesn't work though.

**Comment by risacher** [comment]
There is a paste button in the Firefox all-purpose dropdown menu, just above the "zoom-in +", which works with xterm.js, when using Firefox-on-windows.

**Comment by ragamuffin-coder** [comment]
Ctrl + Insert to copy
Shift + Insert to paste

**Comment by marcosnils** [comment]
:thumbsup:

**Comment by alaagalal** [comment]
ctrl+shift+c ....this is command open inspector of the page 
using Ubuntu+Firefox
 is there another command or solution for that?

**Comment by marcosnils** [comment]
@alaagalal yes. Use ctrl + insert to copy and shift + insert to paste.

**Comment by filips123** [comment]
Is it possible to just use Ctrl+C and Ctrl+V for copying and pasting?

**Comment by marcosnils** [comment]
Nope because the browser overrides it. You need to use ctrl + insert and shift + insert

**Comment by marcosnils** [comment]
Nope because the browser overrides it. You need to use ctrl + insert and shift + insert

**Comment by mgglamblin** [comment]
It's quite strange. ctrl+insert doesn't work for copying and shift+insert works for pasting. What can I check for getting more data? Thanks

**Comment by akki-15** [comment]
> 
> 
> Ctrl + Insert to copy
> Shift + Insert to paste

this worked perfectly fine for me

**Comment by bruecp** [comment]
Hi, 
I am facing the same problem on Win10. I tried all mentioned tricks in the browsers Chrome, Firefox and Edge.
The editor (e.g. Nano, Vim) inside a PWD master is blocking as far as the Shift+Insert or context menu function for paste is used. 
Furthermore, I tried this also on another laptop (Win 7) with the same negative result.

I tried some other solutions like, using the PWD Editor, but there I can just drag the file, which I would like to upload and see it's content. Further functions like import, save, etc. is not available.

Lastly I tried to use Putty / WinScp to upload the config file (docker-compose.yaml) but this attempt, fails during establishing the ssh connection, with the error " server send pubic-key".

Some other ideas, to upload or paste file contents to PWD?
Thanks and BR,
Peter

**Comment by marcosnils** [comment]
> I tried some other solutions like, using the PWD Editor, but there I can just drag the file, which I would like to upload and see it's content. Further functions like import, save, etc. is not available.

You can just drag & drop a file into the terminal and it'll get uploaded to the current working directory you're standing in. 


> I am facing the same problem on Win10. I tried all mentioned tricks in the browsers Chrome, Firefox and Edge.

Strange.. I've tested window setups in the past and never seen issues with copy / paste. I don't have a windows machine, but once I get one I'll try to repro

**Comment by bruecp** [comment]
Thanks a lot. Drag & Drop into the terminal window did the job. Great.

**Comment by amakumar-beep** [comment]
to copy (CTRL+INSERT)
to paste (SHIFT+INSERT)

**Comment by anshumaanbakshi** [comment]
in 2021 following 2 works well

Ctrl + Insert to copy
Shift + Insert to paste

**Comment by Huaccha** [comment]
thanks marcos

**Comment by nikhil1391** [comment]
> The following worked for me using Microsoft Edge browser CTRL + FN + E to copy CTRL + SHIFT + v to paste

Thanks This works

**Comment by nelimawawire** [comment]
> The following worked for me using Microsoft Edge browser CTRL + FN + E to copy CTRL + SHIFT + v to paste

Thank you! This works.

**Comment by prasad1987** [comment]
on windows with MS-Edge browser following cmd will work

COPY with ctrl+Insert+ c Paste with ctrl+SHift+v

**Comment by santiagortiiz** [comment]
I have a hp elitebook 840 g8 and it's keyboard does not have the INS key, what else should I do to perform the copy command?

**Comment by niks2121** [comment]
> to copy (CTRL+INSERT) to paste (SHIFT+INSERT)

Not working in chrome.
Only ctrl+shift+v working for paste but unable to find copy shortcut.

**Comment by GitHub30** [comment]
> to copy (CTRL+INSERT) to paste (SHIFT+INSERT)

Working in Chrome on Windows 11👍

**Comment by alanmarque** [comment]
> @marcosnils after trying harder, it seems that CTRL+SHIFT+V work on Chrome, but CTRL+SHIFT+C opens the Chrome console panel instead of copy stuff

Thanksssss

**Comment by Jasveer-Shah** [comment]
I am on window 10, browser chrome
labs.play-with-docker.com provides linux 
the commands worked for me are - 
  for copy       ct+fn+insert
  for paste      ct+shift+v

**Comment by g-u-r-k-a-n** [comment]
> Ctrl+shift+c/v sent from mobile
> […](#)
> 

If you are using a browser like Opera, this shortcut is a bit of a torture :) Because they are shortcut for developer tools.
I suppose that ctrl & shift + insert is useful in all browser.

**Comment by g-u-r-k-a-n** [comment]
> Ctrl+shift+c/v sent from mobile
> […](#)
>  

@marcosnils If you are using a browser like Opera, this shortcut is like a bit torture :) Because they are shortcut for developer tools.
I suppose that ctrl & shift + insert is useful in all browser.

**Comment by IndunilPrasha** [comment]
> > Ctrl + Insert to copy
> > Shift + Insert to paste
> 
> this worked perfectly fine for me

Thanks. this is working windows 10 in crome

**Comment by stephenjohnson9** [comment]
Microsft Edge 
CTRL + FN + E to copy (couldn't get to work)

CTRL + SHIFT + v to paste (worked)

Chrome (Both commands worked)

Ctrl + Insert to copy
Shift + Insert to paste

**Comment by neon-symeon** [comment]
> to copy (CTRL+INSERT) to paste (SHIFT+INSERT)
simple, great and useful. may thanks

**Comment by bmondal98** [comment]
> I am on window 10, browser chrome labs.play-with-docker.com provides linux the commands worked for me are - for copy ct+fn+insert for paste ct+shift+v

yes its working for me on windows machine

**Comment by shubham-sihasane** [comment]
Windows Operating System | Chrome Browser

1. COPY = CONTROL + INSERT
2. PASTE = SHIFT + INSERT
