### ISSUE TITLE
Keep online and github versions in sync

### ISSUE THREAD

**Issue by scornelissen85** [franela/play-with-docker#69]
This is not an issue, but more of an possible improvement. I saw that the on-line variant was using a newer version of dind, with Docker 1.13.0-rc3, while the Dockerfile in this github was based on 1.13.0-rc2. THis version is also the version on the Docker hub.

Is it possible to keep the code on github, the image on Docker hub and the on-line variant on play-with-docker.com in sync? The code is already there, I think as it is running on play-with-docker.com. Maybe on a seperate (develop/unstable) branch?

**Comment by marcosnils** [comment]
Sure, my bad. I'll update the Dockerfile soon

**Comment by scornelissen85** [comment]
No problem, I'm happy with what I see and can run already. But I had trouble on getting docker 1.13.0-rc3 running on my own.

Thanks for the fast response.

**Comment by marcosnils** [comment]
Done a4424be83eb5f9b8a8cbdb48b6c20b6eb3ac744e. We'll make our best to keep the code in sync to what's in prod.
