### ISSUE TITLE
Add central database to store app metadata

### ISSUE THREAD

**Issue by marcosnils** [franela/play-with-docker#8]
The idea to horizontally scale nodes (docker daemons and webapp). In order to do this we need a centralized DB ( maybe redis?) where session information and node state is stored and shared across nodes.

There are several //TODO's in the code to improve this.

**Comment by xetorthio** [comment]
It seems like we won't need this for now as we won't centralize anything. Each host will store the sessions it knows about. And the request will go directly to that host. Like: `host1.play-with-docker.com`
