### ISSUE TITLE
level=error msg="'overlay2' is not supported over overlayfs"

### ISSUE THREAD

**Issue by allamand** [franela/play-with-docker#83]
Hello,

I try to use the play-with-docker on ubuntu 16.04 with docker with overlay2.

When building image from Dockerfile.dind, then launching it via PWD, I got this error : 
```
level=error msg="'overlay2' is not supported over overlayfs"
```
I had similair error with 
```
level=error msg="'overlay2' is not supported over aufs"
```

Which driver to you uses for you PWD instance ?

Thanks

**Comment by marcosnils** [comment]
You can use devicemapper or ZFS over overlay2
