### ISSUE TITLE
unable to get to exposed services when running locally

### ISSUE THREAD

**Issue by cglewis** [franela/play-with-docker#89]
Is there something else that needs to be configured or setup for service discovery/proxying?

From the README:
```
If you need to access your services from outside, use the following URL pattern http://ip<underscore_ip>-<port>.play-with-docker.com (i.e: http://ip10_2_135_3-80.play-with-docker.com/).
```

However, when running locally using `make`, exposed services redirect to URLs such as:

```
http://ip10_0_0_3-32768.192.168.99.103:3000/
```

Which doesn't work.  What else needs to be set and/or run for this to work?

**Comment by scornelissen85** [comment]
You need a dns server which will forward *.docker.domain to your server with PWD. It won't work directly on ip addresses.

**Comment by cglewis** [comment]
ah, thanks @scornelissen85.  closing.

**Comment by marcosnils** [comment]
> You need a dns server which will forward *.docker.domain to your server with PWD. It won't work directly on ip addresses.

That's correct. You can add 192.168.99.103 to your `hosts` OS file and then use that name to access the service.
