### ISSUE TITLE
Access-Control-Allow-Origin fails when docker container sends "*" as Header Value

### ISSUE THREAD

**Issue by cookiengineer** [franela/play-with-docker#96]
The play-with-docker containers will override the value with the container's URL. If the project inside the container returns "*", it will fail in Chrome and Firefox, because sending the header two times with different values is not allowed as per specification.

Example error in Chrome:

```
XMLHttpRequest cannot load http://pwd10_0_9_3-8080.play-with-docker.com:4848/api/project/index. The 'Access-Control-Allow-Origin' header contains multiple values 'http://pwd10_0_9_3-8080.play-with-docker.com, *', but only one is allowed. Origin 'http://pwd10_0_9_3-8080.play-with-docker.com' is therefore not allowed access.
```

The header is **added** by play-with-docker and **not overwritten** which means there will be two times the `Access-Control-Allow-Origin` header transmitted over the network. You can see that in Chrome via the Network Tab's Header Inspector:

![https://i.imgur.com/Y4VW98l.png](https://i.imgur.com/Y4VW98l.png)

**Comment by marcosnils** [comment]
@cookiengineer what did you run in the container?. As running some other basic apps doesn't add the Allow-Origin header. I'm wondering if whatever you're running in PWD might be causing this.

Is there a way I can easily reproduce?

**Comment by cookiengineer** [comment]
I'm not sure if that's an easy way to reproduce, but you can use the same docker command as I tried out with the lycheejs container:

```bash
$ docker run --publish 4848:4848 --publish 8080:8080 cookiengineer/lycheejs
```

It still is broken but it seems to behave differently now, despite having nothing changed in the docker image. Was there a change in the NAT behaviour? The container and the software inside runs under the assumption that there are two public ports, `8080` and `4848`, reachable under the same host. 8080 can be modified to whatever port, but 4848 has to be there as it serves the public API.

I see that the concept of play-with-docker tries to map published ports to different hostnames, so I guess that's why the request to `somethingrandom-8080...:4848` caused the trouble in the first place?

Is there a way to publish all ports on the same host in play-with-docker or wouldn't that be possible?

**Comment by marcosnils** [comment]
> Was there a change in the NAT behaviour?

Yes, we forgot to add something, just re-applied it and I'm getting the same error as you. I'll investigate and check what can be done. Thx for reportiing!.

**Comment by cookiengineer** [comment]
Awesome, just let me know where I can help :)

**Comment by marcosnils** [comment]
@cookiengineer just deployed a version that fixes this. Can you please give it a try and close if it works?

Thx!.

**Comment by cookiengineer** [comment]
Awesome! Tested and verified, works like a charm!
