### ISSUE TITLE
Add shortcut presets selection

### ISSUE THREAD

**Issue by xetorthio** [franela/play-with-docker#98]
Discussion started in #97 and moved here.

**Comment by xetorthio** [comment]
I think adding a minimal thing to begin with should be fine.
Probably having 2 options for now: linux and mac.
And maybe somehow to see which are the shortcuts could be nice too.

**Comment by mikesir87** [comment]
Mk.  Since I'm not on Linux all too often, what shortcuts that should be bound?

**Comment by marcosnils** [comment]
@mikesir87 linux shortcuts work fine as it is, so I guess we can start with a mac preset for the moment.

**Comment by mikesir87** [comment]
Sounds good!  Feel free to assign this to me if you want. I'll try to get something to you soon.

**Comment by marcosnils** [comment]
Closed by #99
